services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: |
      sh -c "yarn install && yarn start"
    restart: "no"
    env_file:
      - ".env"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: |
        sh -c "bundle exec rails db:create db:migrate && rails server --binding=0.0.0.0"
    restart: "no"
    env_file:
      - ".env"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    ports:
      - "3001:3000"
  postgres:
    image: postgres:12.11-alpine
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:7.0-alpine
    env_file:
      - ".env"
    volumes:
      - redis-data:/data:rw
  proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - api
    restart: always
volumes:
  postgres-data:
  redis-data:
